[package]
name = "nova"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.0"
chumsky = "1.0.0-alpha.6"
clap = { version = "4.5.0", features = ["derive"] }
flate2 = "1.0.28"
exolvl = { git = "https://github.com/skycloudd/exolvl/", version = "0.4.0" }
rustc-hash = "1.1.0"
