[package]
name = "nova"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.6"
chumsky = "1.0.0-alpha.6"
clap = { version = "4.5.3", features = ["derive"] }
codespan-reporting = "0.11.1"
heck = "0.5.0"
rustc-hash = "1.1.0"
snake_case = "0.3.1"
