name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build, Test and Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
            - run: mdbook build book -d output && mdbook test book
            - uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: output
